### ISSUE TITLE
strange UI in iterm2

### ISSUE THREAD

**Issue by 1330571** [LionyxML/nocurses#2]
![image](https://user-images.githubusercontent.com/30896780/67372020-d4d01780-f5af-11e9-901f-0acd84766f5c.png)
why there are always background color in the strings output.
I haven't met any similar issues before. 
I use "gcc -std=c11 -o" to compile demo.c

**Comment by LionyxML** [comment]
This happens because in this demo, we are forcing the background to be black (ANSI BLACK) when printing.

On iterm2, go to:
Profiles -> edit profiles -> click in your current profile (default is default) -> Colors

What is there as background for you? On the right column you'll see also that black is diferent when used on the BRIGHT settings. You'll probably have to change the nocurses.h black to the color you're using on your system.

:)
